name: Test
on: [push, pull_request]

jobs:
  tests:
    name: PHPUnit PHP ${{ matrix.php }} ${{ matrix.dependency }} (Symfony ${{ matrix.symfony }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
        symfony:
          - '5.4.*'
          - '6.0.*'
          - '6.1.*'
          - '6.2.*'
          - '6.3.*'
          - '6.4.*'
          - '7.0.*'
        exclude:
          - php: '8.1'
            symfony: '7.0.*'
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov
          tools: flex

      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Update project dependencies
        run: composer update --no-progress --ansi --prefer-stable

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: Prepare PHPUnit config
        run: cp phpunit.xml.dist phpunit.xml

      - name: Run tests
        run: vendor/bin/phpunit